# Generated by Django 5.0.6 on 2024-06-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_images_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='images',
        ),
    ]
