# Generated by Django 5.0.6 on 2024-06-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_images_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='filter_price',
        ),
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.DeleteModel(
            name='brand',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='filter_price',
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
