# Generated by Django 5.0.6 on 2024-06-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
