# Generated by Django 5.0.6 on 2024-07-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sale'), ('50% Off', '50% Off'), ('75% Off', '50% Off')], max_length=100),
        ),
    ]
