# Generated by Django 5.0.6 on 2024-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sale'), ('50% Off', '50% Off'), ('75% Off', '75% Off')], max_length=100),
        ),
    ]
