# Generated by Django 5.0.6 on 2024-07-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
