# Generated by Django 4.2.5 on 2024-07-12 08:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0029_cart_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='Cart1',
        ),
    ]
