# Generated by Django 4.2.5 on 2024-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_cart1_image_cart1_name_cart1_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
