# Generated by Django 4.2.5 on 2024-07-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_cart1_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart1',
            name='item',
        ),
    ]
