# Generated by Django 4.2.5 on 2024-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_remove_cart1_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
