# Generated by Django 4.2.5 on 2024-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_cart1_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='sbt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart1',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
