# Generated by Django 4.2.5 on 2024-07-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_cart1_sbt_alter_cart1_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='sbt',
            field=models.IntegerField(default=None),
        ),
    ]
