# Generated by Django 4.2.5 on 2024-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_cart1_sbt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cart1',
            name='quantity',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
