# Generated by Django 4.2.5 on 2024-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_cart1_price_alter_cart1_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
