# Generated by Django 5.0.6 on 2024-07-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_remove_cart1_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
    ]
