# Generated by Django 5.0.6 on 2024-07-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_cart1_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
    ]
