# Generated by Django 5.0.6 on 2024-07-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_cart1_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product_color'),
        ),
    ]
