# Generated by Django 5.0.6 on 2024-07-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_rename_color_cart1_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='product_color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.product_color'),
        ),
    ]
