# Generated by Django 5.0.6 on 2024-07-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_cart1_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product_color'),
        ),
    ]
