# Generated by Django 5.0.6 on 2024-07-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_rename_color_product_color_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_color',
            old_name='product_color',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='cart1',
            name='product_color',
        ),
    ]
