# Generated by Django 4.2.5 on 2024-07-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_cart1_clr'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalStock',
            field=models.IntegerField(default=0),
        ),
    ]
