# Generated by Django 4.2.5 on 2024-07-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_product_totalstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='item',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
