# Generated by Django 4.2.5 on 2024-07-15 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_cart1_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
