# Generated by Django 4.2.5 on 2024-07-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_alter_cart1_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='totalStock',
        ),
    ]
